jobs:
  include:
    - stage: test_backend
      language: php
      php:
        - 7.4
      cache:
        directories:
          - vendor
      before_script:
        - cd backend
        - composer self-update
        - composer install --prefer-source --no-interaction --dev
      script: phpunit --configuration phpunit.xml --coverage-text
