swagger: "2.0"
info:
  title: "Vocabulary"
  description: "Vocabulary"
  version: "1.0"

host: api.vocabulary.local
basePath: /api/v1
schemes:
  - https

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Authentikáció
      produces:
        - application/json
      parameters:
        - in: body
          name: auth
          schema:
            $ref: "#/definitions/Login"
      responses:
        200:
          description: Sikeres belépés
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              errors:
                default: [ ]
                example: [ ]
              user:
                $ref: '#/definitions/AuthUserResponse'
              token:
                $ref: '#/definitions/AuthToken'
        400:
          description: Sikertelen belépés. Validálási probléma, az elküldött email cím, jelszó nem felel meg a validálási követelményeknek.
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: false
              errors:
                example: [
                    "validator": [
                        "email": [
                            "Email cím mező kitöltése kötelező!",
                            "Hibás email formátum!",
                        ],
                        "password": [
                            "A jelszó nem felel meg a követelményeknek!"
                        ]
                    ]
                ]
        401:
          description: Sikertelen belépés, hibás felhasználói adatok
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: false
              errors:
                example: [
                    "auth": [
                        "Hibás belépési adatok vagy nem létezik a felhasználó!",
                    ]
                ]
  /auth/register:
    post:
      tags:
        - Auth
      summary: Regisztráció
      produces:
        - application/json
      parameters:
        - in: body
          name: auth
          schema:
            $ref: "#/definitions/Register"
      responses:
        200:
          description: Sikeres regisztráció
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              errors:
                items:
                  type: string
                default: [ ]
                example: [ ]
        400:
          description: Sikertelen regisztráció. Validálási probléma, az elküldött adatok nem felelnek meg a validálási követelményeknek.
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: false
              errors:
                example: [
                    "validator": [
                        "fullname": [
                            "Mező kitöltése kötelező",
                        ],
                        "email": [
                            "Email cím mező kitöltése kötelező!",
                            "Ezzel az email címmel már korábban regisztráltak",
                            "Hibás email formátum!",
                        ],
                        "password": [
                            "A jelszó nem felel meg a követelményeknek!",
                            "A két jelszó nem egyezik"
                        ],
                        "password_confirmation": [
                            "A jelszó nem felel meg a követelményeknek!",
                            "A két jelszó nem egyezik"
                        ]
                    ]
                ]

  /dictionary:
    get:
      summary: Visszatér a felhasználó álltal létrehozott szótárakkal
      security:
        - Bearer: [ ]
      tags:
        - Dictionary
      produces:
        - application/json
      responses:
        200:
          description: Visszatér a felhasználó álltal létrehozott szótárakkal
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'

            properties:
              success:
                example: true
              errors:
                items:
                  type: string
                default: [ ]
                example: [ ]
              dictionaries:
                type: array
                items:
                  $ref: '#/definitions/Dictionary'
                example: [
                  {
                    "id": 1,
                    "name": "Angol - Magyar színek és számok",
                    "knownLanguage": "Magyar",
                    "foreignLanguage": "Angol",
                    "shared": true
                  },
                  {
                    "id": 2,
                    "name": "Angol - Magyar IT kifejezések",
                    "knownLanguage": "Magyar",
                    "foreignLanguage": "Angol",
                    "shared": false
                  },
                ]
        401:
          description: A felhasználó nincs bejelentkezve
          schema:
            allOf:
              - $ref: '#/definitions/UnautorizedResponse'
    post:
      summary: Új szótár létrehozása
      tags:
        - Dictionary
      security:
        - Bearer: [ ]
      produces:
        - application/json
      responses:
        201:
          description: Szótár sikeresen létrehozva
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: true
              errors:
                default: []
        400:
          description: Nem lehet létrehozni a szótárat mert hiányoznak szükséges mezők vagy nem felelnek meg az adatok a követelményeknek
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: false
              errors:
                example: [
                    "validator": [
                        "name": [
                            "Mező kitöltése kötelező",
                            "A minimum karakter hossz nem éri el a 2 hosszt!"
                        ],
                        "knownLanguage": [
                            "Mező kitöltése kötelező",
                            "A minimum karakter hossz nem éri el a 1 hosszt!"
                        ],
                        "foreignLanguage": [
                            "A jelszó nem felel meg a követelményeknek!",
                            "A minimum karakter hossz nem éri el a 1 hosszt!"
                        ]
                    ]
                ]
        401:
          description: A felhasználó nincs bejelentkezve
          schema:
            allOf:
              - $ref: '#/definitions/UnautorizedResponse'

  /dictionary/{id}:
    get:
      summary: Adott szótárhoz tartozó szavak lekérdezése
      tags:
        - Dictionary
      security:
        - Bearer: [ ]
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Szótár ID
          type: integer
          required: true
      responses:
        200:
          description: Visszatér a szótár adataival és a szótárban található szavakkal.
          schema:
            allOf:
              - $ref: '#/definitions/Dictionary'
        401:
          description: A felhasználó nincs bejelentkezve
          schema:
            allOf:
              - $ref: '#/definitions/UnautorizedResponse'
        403:
          description: Olyan szótárat próbál elérni a felhasználó ami nem az ő tulajdona.
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: false
              errors:
                example: [ "Nincs hozzáférésed az alábbi szótárhoz!" ]
        404:
          description: Nincs ilyen ID-ú szótár.
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: false
              errors:
                example: [ "Nincs ilyen szótár!" ]
    delete:
      summary: Törli az adott szótárat és a hozzá csatolt szavakat is.
      tags:
        - Dictionary
      security:
        - Bearer: [ ]
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Szótár ID
          type: integer
          required: true
      responses:
        201:
          description: Szótár és a hozzá tartozó szavak sikeresen törölve
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: true
              errors:
                default: []
        401:
          description: A felhasználó nincs bejelentkezve
          schema:
            allOf:
              - $ref: '#/definitions/UnautorizedResponse'
        403:
          description: Olyan szótárat próbál elérni a felhasználó ami nem az ő tulajdona.
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: false
              errors:
                example: [ "Nincs hozzáférésed az alábbi szótárhoz!" ]
        404:
          description: Nincs ilyen ID-ú szótár.
          schema:
            allOf:
              - $ref: '#/definitions/StatusResponse'
            properties:
              success:
                default: false
              errors:
                example: [ "Nincs ilyen szótár!" ]


definitions:
  Login:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        example: 'user@email.hu'
      password:
        type: string
        example: 'SzuperTitkosJ31$z0'
  Register:
    type: object
    required:
      - email
      - firstname
      - lastname
      - password
      - password_confirmation
    properties:
      fullname:
        type: string
        example: 'Legyek Réka Matilda'
      email:
        type: string
        example: 'matilda.legyek.rekak@gmail.com'
      password:
        type: string
        example: 'R€kAJ3Ł$zav4VagyOk'
      password_confirmation:
        type: string
        example: 'R€kAJ3Ł$zav4VagyOk'
  Dictionary:
    type: object
    required:
      - name
      - knownLanguage
      - foreignLanguage
    properties:
      id:
        type: integer
      name:
        type: string
        description: Szótár megnevezése
        example: "Angol - Magyar színek és számok"
      knownLanguage:
        type: string
        description: Felhasználó anyanyelve / ismert nyelve
        example: Magyar
      foreignLanguage:
        type: string
        description: Felhasználó tanulni kívánt nyelve
        example: Angol
      shared:
        type: boolean
        description: Szótár megvan osztva a többi felhasználóval?
        example: false
      words:
        type: array
        items:
          type: object
          allOf:
            - $ref: '#/definitions/Word'
  Word:
    type: object
    properties:
      id:
        type: integer
      knownLanguage:
        type: string
        example: sárga
      foreignLanguage:
        type: string
        example: yellow

  StatusResponse:
    type: object
    required:
      - success
    properties:
      success:
        type: boolean
      errors:
        type: array
        items:
          type: string

  AuthUserResponse:
    type: object
    description: Felhasználó adatai
    properties:
      id:
        type: integer
      email:
        type: string
      fullName:
        type: string
  AuthToken:
    type: object
    description: Authentikációs token
    properties:
      token:
        type: string
        example: "eyJ0eXAiOiJKV.....0zk6uSrak7uqIA"
      expire:
        type: integer
        example: 1636000000

  UnautorizedResponse:
    type: object
    description: A felhasználó nincs bejelentkezve, vagy olyan műveletet próbál végrehajtani, amihez nincs engedélye
    allOf:
      - $ref: '#/definitions/StatusResponse'
    properties:
      success:
        default: false
        example: false
      errors:
        default: [ "Felhasználó nincs bejelentkezve!" ]
        example: [ "Felhasználó nincs bejelentkezve!" ]

