api_controllers:
    resource: ../../src/Controller/API/
    type: annotation
    prefix: '/api/v1/'

frontend_controllers:
    resource: ../../src/Controller/Frontend/
    type: annotation
    prefix: '/'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
